# Tensorflow2 Zero to GANs

### This notebook is a port of https://jovian.ml/aakashns/01-pytorch-basics

##### Part one of **Tensorflow: Zero to GANs**

1. [Tensorflow Basics: Tensors & Gradients](https://jovian.ml/kartik.godawat/01-tensorflow-basics)
2. [Linear Regression & Gradient Descent](https://jovian.ml/kartik.godawat/02-tf-linear-regression)
3. [Image Classfication using Logistic Regression](https://jovian.ml/kartik.godawat/03-tf-logistic-regression) 
4. [Training Deep Neural Networks on a GPU](https://jovian.ml/kartik.godawat/04-tf-feedforward-nn)

With eager execution enabled by default in Tensorflow v2, many parallels can now be drawn between torch and tensorflow, enabling developers to learn and utilize both of these powerful frameworks relatively quicker than before.

I'll be taking a Tensorflow first approach in the notebooks, drawing parallels from torch wherever possible and also highlighting the differences between the two. It is highly recommended that this notebook be viewed with [PyTorch basics notebook](https://jovian.ml/aakashns/01-pytorch-basics) for clearer understanding

### Tensorflow Basics: Tensors & Gradients

This series attempts to make Tensorflow a bit more approachable for people starting out with deep learning and neural networks. In this notebook, we’ll cover the basic building blocks of Tensorflow models: tensors and gradients.

In [1]:
## System setup - #TODO--system-setup

We begin by importing Tensorflow2:

In [2]:
# Uncomment the command below if Tensorflow is not installed
# pip install tensorflow
# !conda install pytorch cpuonly -c pytorch -y #TODO--conda install

In [3]:
import tensorflow as tf # Importing as "tf" is convention, like np for numpy, pd for pandas

# Tensors

At its core, Tensorflow is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In contrast with PyTorch, here a tensor can be defined as multiple types, we will start with one of the types called **`tf.constant`** and use other types as need arises.

In [4]:
t0 = tf.Variable(4.)
t0

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>

In [5]:
t1 = tf.constant(4.)
t1

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

Here, **4.** is a shorthand for **4.0**. It is used to indicate to Python (and Tensorflow) that you want to create a floating point number. We can verify this by checking the dtype attribute of our tensor:


In [6]:
t1.dtype

tf.float32

Let's try creating slightly more complex tensors:


In [7]:
t2 = tf.constant([1.,2,3,4])
t2

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

In [8]:
t3 = tf.constant([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]], dtype=float32)>

In [9]:
t4 = tf.constant([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[11., 12., 13.],
        [13., 14., 15.]],

       [[15., 16., 17.],
        [17., 18., 19.]]], dtype=float32)>

Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the **`.shape`** property of a tensor.

In [10]:
print(t1)
t1.shape

tf.Tensor(4.0, shape=(), dtype=float32)


TensorShape([])

In [11]:
print(t2)
t2.shape

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


TensorShape([4])

In [12]:
print(t3)
t3.shape

tf.Tensor(
[[ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]], shape=(3, 2), dtype=float32)


TensorShape([3, 2])

In [13]:
print(t4)
t4.shape

tf.Tensor(
[[[11. 12. 13.]
  [13. 14. 15.]]

 [[15. 16. 17.]
  [17. 18. 19.]]], shape=(2, 2, 3), dtype=float32)


TensorShape([2, 2, 3])

### Tensor operations and gradients
We can combine tensors with the usual arithmetic operations. Let's look an example:

#### Constant vs Variables
In tf.constant, the value cannot be changed after being initialized. i.e. it is immutable
However, if we want to assign or change values at a later stage, we need to declare using **`tf.Variable`**

In [14]:
x = tf.constant(3.)
w = tf.Variable(4.)
b = tf.Variable(5.)
x, w, b

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.0>,
 <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>)

Gradient calculation works differently in tensorflow than torch, 

In PyTorch, gradients are kept within the variables themselves like `x.grad`, which could be calculated by using `.backward()` method. Refer the [pytorch notebook](https://jovian.ml/aakashns/01-pytorch-basics/v/18#C19)

In tensorflow, tf.GradientTape is used to record the operations for automatic differentiation.
In the code below, we perform the operation within the 'scope' of the gradienttape and then view the gradients by calling `tape.gradient(A,B)` to find `dA/dB`

In [15]:
with tf.GradientTape(persistent=True) as tape:
    y = w * x + b
print(tape.gradient(y, x))
print(tape.gradient(y, w))
print(tape.gradient(y, b))

None
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


Because `x` was defined as a constant here, `dy/dx` is not computable. 
As expected, dy/dw has the same value as x i.e. 3, and dy/db has the value 1. Gradient is simply another term for derivative.

### Interoperability with Numpy
[Numpy](http://www.numpy.org/) is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

- [Matplotlib](https://matplotlib.org/) for plotting and visualization
- [OpenCV](https://opencv.org/) for image and video processing
- [Pandas](https://pandas.pydata.org/) for file I/O and data analysis

Instead of reinventing the wheel, Tensorflow also interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy:

In [16]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a Tensorflow tensor by calling `tf.convert_to_tensor`.

In [17]:
y = tf.convert_to_tensor(x)
y

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

Conversion is also handled implicitly by tf while declaring new variables

In [18]:
y = tf.constant(x)
y

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

Let's verify that the numpy array and tf tensor have similar data types.

In [19]:
x.dtype, y.dtype

(dtype('float64'), tf.float64)

We can convert a tf tensor to a Numpy array using the .numpy method of a tensor.

In [20]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between Tensorflow and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.



### Commit and upload the notebook
As a final step, we can save and commit out work using the jovian library.

In [1]:
import jovian

In [ ]:
jovian.commit(filename="01-tensorflow-basics", environment=None)

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
